# -*- coding: utf-8 -*-
"""Banco de 100 preguntas esenciales para el examen CCNA 200-301.

Cada pregunta: d = dominio, q = enunciado, o = opciones, a = índice correcto, e = explicación.
La distribución sigue los pesos del blueprint oficial:
  Fundamentos de Red 20 | Acceso a la Red 20 | Conectividad IP 25
  Servicios IP 10 | Fundamentos de Seguridad 15 | Automatización 10
"""

FUND = "Fundamentos de Red"
ACC = "Acceso a la Red"
IPC = "Conectividad IP"
SRV = "Servicios IP"
SEG = "Seguridad"
AUT = "Automatización"

QUESTIONS = [
    # ------------------- Fundamentos de Red (20) -------------------
    {"d": FUND, "q": "¿En qué capa del modelo OSI opera un switch tradicional al reenviar tramas según la dirección MAC?",
     "o": ["Capa 1 - Física", "Capa 2 - Enlace de datos", "Capa 3 - Red", "Capa 4 - Transporte"], "a": 1,
     "e": "El switch aprende y reenvía según direcciones MAC, que pertenecen a la Capa 2 (Enlace de datos)."},
    {"d": FUND, "q": "¿Qué protocolo de transporte es orientado a conexión y garantiza la entrega mediante acuses de recibo?",
     "o": ["UDP", "ICMP", "TCP", "ARP"], "a": 2,
     "e": "TCP establece conexión (three-way handshake) y usa ACKs, secuencias y retransmisiones para garantizar la entrega."},
    {"d": FUND, "q": "¿Cuál es la dirección de broadcast de la red 192.168.10.64/26?",
     "o": ["192.168.10.95", "192.168.10.127", "192.168.10.63", "192.168.10.255"], "a": 1,
     "e": "/26 = bloques de 64. La subred 192.168.10.64 abarca .64-.127, por lo que el broadcast es .127."},
    {"d": FUND, "q": "¿Cuántas direcciones de host utilizables tiene una subred /27?",
     "o": ["30", "32", "62", "14"], "a": 0,
     "e": "/27 deja 5 bits de host: 2^5 = 32 direcciones, menos red y broadcast = 30 hosts utilizables."},
    {"d": FUND, "q": "¿Cuál de estos rangos es una dirección IPv4 privada según RFC 1918?",
     "o": ["11.0.0.0/8", "172.32.0.0/16", "192.168.0.0/16", "169.254.0.0/16"], "a": 2,
     "e": "RFC 1918 define 10.0.0.0/8, 172.16.0.0/12 y 192.168.0.0/16. 169.254.0.0/16 es APIPA (link-local)."},
    {"d": FUND, "q": "Un host necesita resolver la dirección MAC asociada a una IP conocida en su LAN. ¿Qué protocolo utiliza?",
     "o": ["DNS", "ARP", "DHCP", "ICMP"], "a": 1,
     "e": "ARP (Address Resolution Protocol) resuelve direcciones IPv4 a direcciones MAC dentro de la LAN."},
    {"d": FUND, "q": "¿Qué tipo de dirección IPv6 comienza con FE80::/10?",
     "o": ["Global unicast", "Unique local", "Link-local", "Multicast"], "a": 2,
     "e": "FE80::/10 identifica direcciones link-local, obligatorias en cada interfaz IPv6 y válidas solo en el enlace."},
    {"d": FUND, "q": "¿Qué comando abrevia la dirección IPv6 2001:0DB8:0000:0000:0000:0000:0000:0001 correctamente?",
     "o": ["2001:DB8::1", "2001:DB8:0:1", "2001:DB8::0::1", "2001:DB8:1"], "a": 0,
     "e": "Se eliminan ceros a la izquierda y se comprime una sola vez la secuencia de ceros con '::' → 2001:DB8::1."},
    {"d": FUND, "q": "¿Qué cable se usa tradicionalmente para conectar dos switches entre sí (sin auto-MDIX)?",
     "o": ["Straight-through", "Crossover", "Rollover", "Coaxial"], "a": 1,
     "e": "Dispositivos similares (switch-switch) requieren cable cruzado (crossover); auto-MDIX moderno lo hace innecesario."},
    {"d": FUND, "q": "¿Cuál es la principal ventaja de la fibra óptica monomodo frente a la multimodo?",
     "o": ["Menor costo", "Mayores distancias de transmisión", "Conectores más pequeños", "Inmunidad al agua"], "a": 1,
     "e": "La fibra monomodo usa láser y un núcleo delgado, alcanzando distancias mucho mayores (decenas de km)."},
    {"d": FUND, "q": "¿Qué campo del encabezado IPv4 evita que un paquete circule indefinidamente por la red?",
     "o": ["Checksum", "TTL", "Flags", "ToS"], "a": 1,
     "e": "El TTL (Time To Live) se decrementa en cada salto; al llegar a 0 el paquete se descarta."},
    {"d": FUND, "q": "¿Qué protocolo usa el puerto TCP 443?",
     "o": ["HTTP", "HTTPS", "SSH", "Telnet"], "a": 1,
     "e": "HTTPS (HTTP sobre TLS) usa el puerto TCP 443. HTTP usa 80, SSH 22 y Telnet 23."},
    {"d": FUND, "q": "En una topología de dos niveles (collapsed core), ¿qué capas del modelo jerárquico se combinan?",
     "o": ["Acceso y distribución", "Núcleo y distribución", "Acceso y núcleo", "WAN y núcleo"], "a": 1,
     "e": "En el diseño collapsed core, las capas de núcleo (core) y distribución se fusionan en un solo nivel."},
    {"d": FUND, "q": "¿Qué máscara de subred permite exactamente 2 hosts utilizables, típica para enlaces punto a punto?",
     "o": ["/29", "/30", "/31", "/32"], "a": 1,
     "e": "/30 deja 2 bits de host: 4 direcciones, 2 utilizables. (/31 también se usa en p2p pero sin red/broadcast)."},
    {"d": FUND, "q": "¿A qué subred pertenece el host 172.16.45.14/20?",
     "o": ["172.16.45.0", "172.16.40.0", "172.16.32.0", "172.16.44.0"], "a": 2,
     "e": "/20 incrementa en bloques de 16 en el tercer octeto: 172.16.32.0 - 172.16.47.255 incluye a 172.16.45.14."},
    {"d": FUND, "q": "¿Qué tecnología permite ejecutar múltiples sistemas operativos aislados sobre un mismo hardware físico?",
     "o": ["VLAN", "Virtualización con hipervisor", "Clustering", "NAT"], "a": 1,
     "e": "Un hipervisor (tipo 1 o 2) crea máquinas virtuales que comparten el hardware físico de forma aislada."},
    {"d": FUND, "q": "¿Cuál es una característica de UDP?",
     "o": ["Entrega garantizada", "Control de flujo por ventanas", "Bajo overhead y sin conexión", "Retransmisión automática"], "a": 2,
     "e": "UDP no establece conexión ni garantiza entrega: su encabezado mínimo lo hace ideal para voz, video y DNS."},
    {"d": FUND, "q": "¿Qué banda Wi-Fi ofrece mayor velocidad pero menor alcance y penetración de obstáculos?",
     "o": ["900 MHz", "2.4 GHz", "5 GHz", "Ambas son iguales"], "a": 2,
     "e": "5 GHz ofrece más canales y velocidad, pero al ser mayor frecuencia se atenúa más con la distancia y obstáculos."},
    {"d": FUND, "q": "¿Cuántos canales no solapados existen en la banda de 2.4 GHz (802.11) en América?",
     "o": ["3 (1, 6, 11)", "11", "5", "8"], "a": 0,
     "e": "En 2.4 GHz solo los canales 1, 6 y 11 no se solapan entre sí, por eso son los recomendados."},
    {"d": FUND, "q": "Un paquete debe llegar a 10.10.10.10. La tabla tiene rutas 10.0.0.0/8, 10.10.0.0/16 y 10.10.10.0/24. ¿Cuál se usa?",
     "o": ["10.0.0.0/8", "10.10.0.0/16", "10.10.10.0/24", "La ruta por defecto"], "a": 2,
     "e": "El router siempre elige la coincidencia de prefijo más largo (longest prefix match): /24 gana sobre /16 y /8."},

    # ------------------- Acceso a la Red (20) -------------------
    {"d": ACC, "q": "¿Qué protocolo de trunking encapsula las tramas con una etiqueta de 4 bytes que incluye el VLAN ID?",
     "o": ["ISL", "802.1Q", "VTP", "DTP"], "a": 1,
     "e": "802.1Q inserta una etiqueta de 4 bytes en la trama Ethernet con el VLAN ID (12 bits). ISL es propietario y obsoleto."},
    {"d": ACC, "q": "¿Qué VLAN transporta las tramas SIN etiquetar en un enlace troncal 802.1Q?",
     "o": ["VLAN 1 siempre", "La VLAN nativa", "La VLAN de administración", "Ninguna, todas van etiquetadas"], "a": 1,
     "e": "La VLAN nativa (configurable con 'switchport trunk native vlan') viaja sin etiqueta por el trunk."},
    {"d": ACC, "q": "¿Qué comando configura un puerto de acceso en la VLAN 10?",
     "o": ["switchport mode trunk", "switchport access vlan 10", "vlan database 10", "switchport trunk vlan 10"], "a": 1,
     "e": "'switchport mode access' + 'switchport access vlan 10' asignan el puerto como acceso en la VLAN 10."},
    {"d": ACC, "q": "¿Cuál es el propósito principal de Spanning Tree Protocol (STP)?",
     "o": ["Balancear tráfico entre VLANs", "Prevenir bucles de Capa 2", "Cifrar tramas", "Agregar ancho de banda"], "a": 1,
     "e": "STP bloquea puertos redundantes para evitar bucles de conmutación y tormentas de broadcast en Capa 2."},
    {"d": ACC, "q": "¿Cómo se elige el root bridge en STP?",
     "o": ["MAC más alta", "Mayor prioridad", "Menor Bridge ID (prioridad + MAC)", "Puerto más rápido"], "a": 2,
     "e": "Gana el switch con el Bridge ID más bajo: primero la prioridad más baja y, en empate, la MAC más baja."},
    {"d": ACC, "q": "¿Qué función cumple PortFast en un puerto de acceso?",
     "o": ["Aumenta la velocidad del puerto", "Pasa el puerto directamente a forwarding", "Bloquea BPDUs", "Activa el trunking"], "a": 1,
     "e": "PortFast omite los estados listening/learning para que los puertos de host pasen de inmediato a forwarding."},
    {"d": ACC, "q": "¿Qué sucede si un puerto con BPDU Guard habilitado recibe una BPDU?",
     "o": ["Se convierte en root port", "Pasa a estado err-disabled", "Reenvía la BPDU", "Cambia a modo trunk"], "a": 1,
     "e": "BPDU Guard protege PortFast: al recibir una BPDU el puerto se apaga (err-disabled) para evitar bucles."},
    {"d": ACC, "q": "¿Qué protocolo negocia dinámicamente la formación de un trunk entre switches Cisco?",
     "o": ["VTP", "DTP", "CDP", "LACP"], "a": 1,
     "e": "DTP (Dynamic Trunking Protocol) negocia el modo trunk. Se recomienda desactivarlo con 'switchport nonegotiate'."},
    {"d": ACC, "q": "¿Qué protocolo estándar (IEEE) negocia la agregación de enlaces en un EtherChannel?",
     "o": ["PAgP", "LACP (802.3ad)", "DTP", "STP"], "a": 1,
     "e": "LACP es el estándar IEEE 802.3ad/802.1AX; PAgP es el equivalente propietario de Cisco."},
    {"d": ACC, "q": "En LACP, ¿qué combinación de modos forma un EtherChannel?",
     "o": ["passive - passive", "active - passive", "auto - auto", "desirable - auto"], "a": 1,
     "e": "LACP: active-active o active-passive forman canal; passive-passive no negocia. Auto/desirable son de PAgP."},
    {"d": ACC, "q": "¿Qué protocolo permite descubrir dispositivos Cisco vecinos conectados directamente?",
     "o": ["LLDP solamente", "CDP", "ARP", "SNMP"], "a": 1,
     "e": "CDP (Cisco Discovery Protocol) es propietario de Cisco; LLDP es la alternativa estándar IEEE 802.1AB."},
    {"d": ACC, "q": "¿Cuál es el modo de violación por defecto de port security?",
     "o": ["Protect", "Restrict", "Shutdown", "Warning"], "a": 2,
     "e": "Por defecto, una violación de port security pone el puerto en err-disabled (modo shutdown)."},
    {"d": ACC, "q": "¿Qué comando guarda dinámicamente las MAC aprendidas por port security en la running-config?",
     "o": ["switchport port-security mac-address sticky", "switchport port-security dynamic", "mac-address-table static", "switchport sticky learn"], "a": 0,
     "e": "El modo 'sticky' convierte las MAC aprendidas dinámicamente en entradas de la configuración."},
    {"d": ACC, "q": "En una arquitectura inalámbrica centralizada, ¿qué dispositivo gestiona los access points ligeros (LWAP)?",
     "o": ["Router", "Switch de núcleo", "WLC (Wireless LAN Controller)", "Servidor RADIUS"], "a": 2,
     "e": "El WLC centraliza la configuración y gestión de los AP ligeros mediante túneles CAPWAP."},
    {"d": ACC, "q": "¿Qué protocolo encapsula el tráfico entre un AP ligero y el WLC?",
     "o": ["GRE", "CAPWAP", "IPsec", "LWAPP únicamente"], "a": 1,
     "e": "CAPWAP (Control And Provisioning of Wireless Access Points) crea túneles de control (UDP 5246) y datos (5247)."},
    {"d": ACC, "q": "¿En qué modo un AP autónomo funciona sin necesidad de un WLC?",
     "o": ["Lightweight", "FlexConnect", "Autonomous", "Monitor"], "a": 2,
     "e": "Un AP en modo autonomous contiene toda su inteligencia local y no requiere controlador."},
    {"d": ACC, "q": "¿Qué estado de puerto STP aprende direcciones MAC pero aún NO reenvía tramas?",
     "o": ["Blocking", "Listening", "Learning", "Forwarding"], "a": 2,
     "e": "En learning el puerto puebla la tabla MAC pero todavía no reenvía tráfico de datos."},
    {"d": ACC, "q": "¿Qué versión de STP asigna una instancia por VLAN y es propietaria de Cisco?",
     "o": ["RSTP (802.1w)", "PVST+", "MSTP (802.1s)", "STP (802.1D)"], "a": 1,
     "e": "PVST+ (y Rapid PVST+) de Cisco ejecuta una instancia de spanning tree independiente por cada VLAN."},
    {"d": ACC, "q": "Un switch recibe una trama con MAC destino desconocida. ¿Qué hace?",
     "o": ["La descarta", "La envía al gateway", "La inunda por todos los puertos de la VLAN excepto el de origen", "La guarda en buffer"], "a": 2,
     "e": "El unknown unicast flooding envía la trama por todos los puertos de la misma VLAN salvo por el que llegó."},
    {"d": ACC, "q": "¿Qué comando muestra las VLANs y los puertos asignados a cada una?",
     "o": ["show interfaces trunk", "show vlan brief", "show mac address-table", "show spanning-tree"], "a": 1,
     "e": "'show vlan brief' lista todas las VLANs, su estado y los puertos de acceso asignados."},

    # ------------------- Conectividad IP (25) -------------------
    {"d": IPC, "q": "¿Cuál es la distancia administrativa (AD) de una ruta estática por defecto?",
     "o": ["0", "1", "90", "110"], "a": 1,
     "e": "Ruta estática = 1. Conectada = 0, EIGRP = 90, OSPF = 110, RIP = 120."},
    {"d": IPC, "q": "¿Cuál es la distancia administrativa de OSPF?",
     "o": ["90", "100", "110", "120"], "a": 2,
     "e": "OSPF tiene AD 110. Menor AD = ruta más confiable cuando hay varias fuentes para el mismo prefijo."},
    {"d": IPC, "q": "¿Qué comando crea una ruta por defecto estática hacia 203.0.113.1?",
     "o": ["ip route 0.0.0.0 0.0.0.0 203.0.113.1", "ip default-network 203.0.113.1", "ip route 255.255.255.255 203.0.113.1", "default-route 203.0.113.1"], "a": 0,
     "e": "'ip route 0.0.0.0 0.0.0.0 <next-hop>' define la ruta por defecto (gateway of last resort)."},
    {"d": IPC, "q": "¿Qué es una ruta estática flotante?",
     "o": ["Una ruta que cambia sola de next-hop", "Una estática con AD mayor que actúa de respaldo", "Una ruta aprendida por DHCP", "Una ruta sin máscara"], "a": 1,
     "e": "Se configura con AD más alta que la ruta principal; solo se instala si la principal desaparece."},
    {"d": IPC, "q": "¿Qué métrica usa OSPF para calcular la mejor ruta?",
     "o": ["Saltos", "Costo basado en ancho de banda", "Retardo y carga", "MTU"], "a": 1,
     "e": "OSPF usa costo = ancho de banda de referencia / ancho de banda de la interfaz (por defecto 100 Mbps de referencia)."},
    {"d": IPC, "q": "¿Cómo se elige el Router ID en OSPF si no está configurado manualmente?",
     "o": ["La IP más baja de cualquier interfaz", "La IP más alta de una loopback; si no hay, la más alta de interfaz física", "Siempre la MAC del router", "La IP de la interfaz más rápida"], "a": 1,
     "e": "Prioridad: router-id manual > loopback más alta > IP física activa más alta."},
    {"d": IPC, "q": "¿Qué paquetes OSPF se usan para descubrir y mantener vecinos?",
     "o": ["Update", "Hello", "Query", "Keepalive"], "a": 1,
     "e": "Los paquetes Hello (multicast 224.0.0.5) descubren vecinos y mantienen las adyacencias."},
    {"d": IPC, "q": "¿Cuáles son los temporizadores Hello/Dead por defecto de OSPF en redes broadcast?",
     "o": ["5/15 segundos", "10/40 segundos", "30/120 segundos", "10/30 segundos"], "a": 1,
     "e": "En redes broadcast y punto a punto: Hello 10 s, Dead 40 s (4x). Deben coincidir entre vecinos."},
    {"d": IPC, "q": "¿Qué parámetro debe coincidir para que dos routers OSPF formen adyacencia?",
     "o": ["Router ID", "Área, temporizadores, máscara de subred y autenticación", "Prioridad", "Costo de interfaz"], "a": 1,
     "e": "Área, subred/máscara, Hello/Dead timers, autenticación y flags de stub deben coincidir. Los Router ID deben ser ÚNICOS."},
    {"d": IPC, "q": "En un segmento multiacceso OSPF, ¿qué router genera los LSA tipo 2 en nombre del segmento?",
     "o": ["El ABR", "El DR (Designated Router)", "El ASBR", "Todos los routers"], "a": 1,
     "e": "El DR representa el segmento multiacceso y reduce las adyacencias; se elige por prioridad y luego Router ID más alto."},
    {"d": IPC, "q": "¿Qué prioridad OSPF impide que un router participe en la elección de DR/BDR?",
     "o": ["0", "1", "100", "255"], "a": 0,
     "e": "Con 'ip ospf priority 0' el router nunca será DR ni BDR."},
    {"d": IPC, "q": "¿Qué comando activa OSPF proceso 1 en todas las interfaces 10.0.0.x?",
     "o": ["network 10.0.0.0 0.0.0.255 area 0", "network 10.0.0.0 255.255.255.0 area 0", "router ospf area 0", "ospf enable 10.0.0.0"], "a": 0,
     "e": "Bajo 'router ospf 1', el comando network usa wildcard mask: 'network 10.0.0.0 0.0.0.255 area 0'."},
    {"d": IPC, "q": "¿Qué comando muestra solo las rutas OSPF de la tabla de enrutamiento?",
     "o": ["show ip ospf neighbor", "show ip route ospf", "show ip protocols", "show ospf routes"], "a": 1,
     "e": "'show ip route ospf' filtra la tabla de enrutamiento mostrando solo las rutas con código O."},
    {"d": IPC, "q": "Un router tiene una ruta OSPF (AD 110) y una estática (AD 1) al mismo destino /24. ¿Cuál instala?",
     "o": ["La OSPF por tener métrica", "La estática por menor AD", "Ambas con balanceo", "Ninguna"], "a": 1,
     "e": "Ante el mismo prefijo exacto, gana la fuente con menor distancia administrativa: la estática (1) sobre OSPF (110)."},
    {"d": IPC, "q": "¿Qué protocolo FHRP es propietario de Cisco y usa una IP virtual con MAC 0000.0C07.ACxx?",
     "o": ["VRRP", "GLBP", "HSRP", "LACP"], "a": 2,
     "e": "HSRP (Hot Standby Router Protocol) es de Cisco; la MAC virtual v1 es 0000.0C07.ACxx (xx = grupo)."},
    {"d": IPC, "q": "En HSRP, ¿qué router reenvía activamente el tráfico del grupo?",
     "o": ["El standby", "El active", "El master", "Todos a la vez"], "a": 1,
     "e": "El router active responde al ARP de la IP virtual y reenvía; el standby toma el rol si el active falla."},
    {"d": IPC, "q": "¿Qué comando estático IPv6 crea una ruta por defecto hacia 2001:DB8::1?",
     "o": ["ipv6 route ::/0 2001:DB8::1", "ipv6 route 0.0.0.0/0 2001:DB8::1", "ip route ::/128 2001:DB8::1", "ipv6 default 2001:DB8::1"], "a": 0,
     "e": "En IPv6 la ruta por defecto se expresa como ::/0."},
    {"d": IPC, "q": "¿Qué mecanismo usa IPv6 en lugar de ARP para descubrir vecinos?",
     "o": ["RARP", "NDP (Neighbor Discovery Protocol)", "DHCPv6", "IGMP"], "a": 1,
     "e": "NDP usa mensajes ICMPv6 (Neighbor Solicitation/Advertisement) para resolver direcciones de Capa 2."},
    {"d": IPC, "q": "¿Qué permite a un host IPv6 autoconfigurar su dirección a partir del prefijo anunciado por el router?",
     "o": ["DHCPv6 stateful", "SLAAC", "NAT66", "ISATAP"], "a": 1,
     "e": "SLAAC (Stateless Address Autoconfiguration) usa los Router Advertisements para generar la dirección automáticamente."},
    {"d": IPC, "q": "¿Cuál describe mejor el proceso de enrutamiento entre VLANs con 'router-on-a-stick'?",
     "o": ["Un router con subinterfaces 802.1Q en un solo enlace troncal", "Un switch L2 con rutas estáticas", "Dos routers en HSRP", "Un router con NAT"], "a": 0,
     "e": "Router-on-a-stick usa subinterfaces (encapsulation dot1Q <vlan>) sobre un único enlace trunk hacia el switch."},
    {"d": IPC, "q": "¿Qué comando en un switch multicapa habilita el enrutamiento de una interfaz como puerto L3?",
     "o": ["switchport mode routed", "no switchport", "ip routing enable", "routed-port"], "a": 1,
     "e": "'no switchport' convierte el puerto en interfaz enrutada L3; además se requiere 'ip routing' global."},
    {"d": IPC, "q": "¿Cuál es el next-hop correcto que examina el router para reenviar un paquete?",
     "o": ["La MAC de origen", "La IP de destino comparada con la tabla de enrutamiento", "El puerto TCP", "El TTL"], "a": 1,
     "e": "El router compara la IP destino con su tabla de enrutamiento y reenvía por la coincidencia más específica."},
    {"d": IPC, "q": "¿Qué significa el código 'S*' en la salida de 'show ip route'?",
     "o": ["Ruta OSPF suprimida", "Ruta estática candidata a default", "Ruta sumarizada", "Ruta secundaria"], "a": 1,
     "e": "S = estática, * = candidata a ruta por defecto (gateway of last resort)."},
    {"d": IPC, "q": "Dos rutas OSPF al mismo destino tienen igual costo. ¿Qué hace el router?",
     "o": ["Descarta una", "Balanceo de carga entre ambas (ECMP)", "Usa solo la primera aprendida", "Genera un error"], "a": 1,
     "e": "OSPF soporta Equal-Cost Multi-Path: instala ambas rutas y balancea el tráfico (por defecto hasta 4)."},
    {"d": IPC, "q": "¿Qué dirección multicast usa OSPF para enviar Hellos a todos los routers OSPF?",
     "o": ["224.0.0.1", "224.0.0.5", "224.0.0.10", "239.0.0.5"], "a": 1,
     "e": "224.0.0.5 = todos los routers OSPF; 224.0.0.6 = DR/BDR. 224.0.0.10 es de EIGRP."},

    # ------------------- Servicios IP (10) -------------------
    {"d": SRV, "q": "¿Qué tipo de NAT traduce muchas IP privadas a una sola pública usando puertos?",
     "o": ["NAT estático", "NAT dinámico", "PAT (NAT overload)", "NAT66"], "a": 2,
     "e": "PAT (Port Address Translation, 'ip nat inside source list ... overload') multiplexa por número de puerto."},
    {"d": SRV, "q": "En NAT, ¿cómo se llama la IP privada del host interno vista desde la red interna?",
     "o": ["Inside global", "Inside local", "Outside local", "Outside global"], "a": 1,
     "e": "Inside local = IP privada real del host; inside global = su representación pública tras el NAT."},
    {"d": SRV, "q": "¿Qué protocolo sincroniza los relojes de los dispositivos de red?",
     "o": ["SNMP", "NTP", "Syslog", "CDP"], "a": 1,
     "e": "NTP (puerto UDP 123) sincroniza la hora; es clave para logs y certificados. Se organiza en estratos (stratum)."},
    {"d": SRV, "q": "¿Cuál es el orden correcto de mensajes en la asignación DHCP (DORA)?",
     "o": ["Discover, Offer, Request, Ack", "Discover, Offer, Reply, Assign", "Detect, Offer, Request, Ack", "Discover, Options, Request, Ack"], "a": 0,
     "e": "DORA: el cliente envía Discover, el servidor Offer, el cliente Request y el servidor confirma con Ack."},
    {"d": SRV, "q": "¿Qué comando permite a un router reenviar peticiones DHCP hacia un servidor en otra subred?",
     "o": ["ip dhcp forward", "ip helper-address <ip-servidor>", "dhcp relay enable", "ip dhcp snooping"], "a": 1,
     "e": "'ip helper-address' en la interfaz convierte los broadcast DHCP en unicast hacia el servidor remoto."},
    {"d": SRV, "q": "¿Qué nivel de severidad syslog corresponde a 'warning'?",
     "o": ["3", "4", "5", "6"], "a": 1,
     "e": "0=emergency, 1=alert, 2=critical, 3=error, 4=warning, 5=notification, 6=informational, 7=debugging."},
    {"d": SRV, "q": "¿Qué versión de SNMP añade autenticación y cifrado?",
     "o": ["SNMPv1", "SNMPv2c", "SNMPv3", "SNMPv2u"], "a": 2,
     "e": "SNMPv3 introduce los modelos de seguridad con autenticación (auth) y cifrado (priv); v1/v2c solo usan community strings."},
    {"d": SRV, "q": "¿Qué protocolo de transferencia de archivos NO requiere autenticación y usa UDP 69?",
     "o": ["FTP", "SFTP", "TFTP", "SCP"], "a": 2,
     "e": "TFTP es minimalista: UDP 69, sin autenticación; común para respaldar IOS y configuraciones."},
    {"d": SRV, "q": "¿Qué mecanismo de QoS descarta o marca el tráfico que excede una tasa contratada?",
     "o": ["Queuing", "Policing", "Marking", "Classification"], "a": 1,
     "e": "El policing limita la tasa descartando o remarcando el exceso; el shaping en cambio lo encola y retrasa."},
    {"d": SRV, "q": "¿Qué campo del encabezado IP se usa para marcar paquetes con DSCP en QoS?",
     "o": ["TTL", "ToS/DiffServ", "Flags", "Protocol"], "a": 1,
     "e": "El byte ToS (ahora DiffServ) del encabezado IPv4 lleva los 6 bits DSCP para clasificar el tráfico."},

    # ------------------- Seguridad (15) -------------------
    {"d": SEG, "q": "¿Qué componen las tres A de AAA?",
     "o": ["Access, Audit, Accounting", "Authentication, Authorization, Accounting", "Authentication, Access, Availability", "Authorization, Audit, Access"], "a": 1,
     "e": "AAA = Autenticación (quién eres), Autorización (qué puedes hacer) y Accounting (registro de lo que hiciste)."},
    {"d": SEG, "q": "¿Qué protocolo AAA cifra todo el paquete y separa autenticación de autorización?",
     "o": ["RADIUS", "TACACS+", "Kerberos", "LDAP"], "a": 1,
     "e": "TACACS+ (TCP 49) cifra todo el cuerpo y separa las funciones AAA; RADIUS solo cifra la contraseña."},
    {"d": SEG, "q": "¿Dónde debe aplicarse idealmente una ACL extendida?",
     "o": ["Lo más lejos posible del origen", "Lo más cerca posible del origen", "Solo en interfaces WAN", "En el destino"], "a": 1,
     "e": "Las ACL extendidas (filtran por origen, destino y puertos) se colocan cerca del origen para no transportar tráfico inútil."},
    {"d": SEG, "q": "¿Qué rango numérico corresponde a las ACL estándar de IPv4?",
     "o": ["1-99 (y 1300-1999)", "100-199", "200-299", "2000-2699"], "a": 0,
     "e": "Estándar: 1-99 y 1300-1999 (solo filtran IP origen). Extendida: 100-199 y 2000-2699."},
    {"d": SEG, "q": "¿Qué regla implícita existe al final de toda ACL?",
     "o": ["permit any", "deny any", "log any", "inspect any"], "a": 1,
     "e": "Toda ACL termina con un 'deny any' implícito: lo no permitido explícitamente se descarta."},
    {"d": SEG, "q": "¿Qué ataque mitiga DHCP snooping?",
     "o": ["ARP spoofing", "Servidores DHCP no autorizados (rogue)", "Desbordamiento de tabla MAC", "Fuerza bruta SSH"], "a": 1,
     "e": "DHCP snooping clasifica puertos en confiables/no confiables y bloquea ofertas DHCP de servidores falsos."},
    {"d": SEG, "q": "¿Qué función usa la base de datos de DHCP snooping para validar paquetes ARP?",
     "o": ["Port security", "DAI (Dynamic ARP Inspection)", "BPDU Guard", "Storm control"], "a": 1,
     "e": "DAI compara los ARP con los bindings IP-MAC de DHCP snooping para bloquear ARP spoofing."},
    {"d": SEG, "q": "¿Qué estándar proporciona control de acceso a la red basado en puertos con autenticación por RADIUS?",
     "o": ["802.1Q", "802.1X", "802.3ad", "802.11i"], "a": 1,
     "e": "802.1X define supplicant (cliente), authenticator (switch/AP) y authentication server (RADIUS)."},
    {"d": SEG, "q": "¿Qué método de cifrado introduce WPA3 para proteger el handshake frente a ataques de diccionario?",
     "o": ["TKIP", "SAE (Simultaneous Authentication of Equals)", "WEP mejorado", "PSK simple"], "a": 1,
     "e": "WPA3 reemplaza el 4-way handshake PSK por SAE, resistente a ataques de diccionario offline."},
    {"d": SEG, "q": "¿Qué comando cifra todas las contraseñas en texto plano de la configuración?",
     "o": ["enable secret", "service password-encryption", "crypto key generate rsa", "password encrypt all"], "a": 1,
     "e": "'service password-encryption' aplica cifrado tipo 7 (débil pero oculta a simple vista) a las contraseñas planas."},
    {"d": SEG, "q": "¿Qué comando es más seguro para proteger el acceso a modo privilegiado?",
     "o": ["enable password", "enable secret", "line password", "username password"], "a": 1,
     "e": "'enable secret' guarda un hash (MD5/scrypt según versión) en lugar de texto plano; siempre prevalece sobre 'enable password'."},
    {"d": SEG, "q": "Un atacante envía correos masivos fingiendo ser un banco para robar credenciales. ¿Qué ataque es?",
     "o": ["Vishing", "Phishing", "Whaling", "Tailgating"], "a": 1,
     "e": "Phishing = suplantación por correo masivo. Vishing usa voz, whaling apunta a ejecutivos, tailgating es acceso físico."},
    {"d": SEG, "q": "¿Qué tipo de VPN cifra el tráfico entre dos sitios completos a través de Internet?",
     "o": ["VPN de acceso remoto", "VPN site-to-site (IPsec)", "VPN SSL clientless", "GRE sin cifrado"], "a": 1,
     "e": "Una VPN site-to-site IPsec conecta redes completas entre gateways; el usuario final no ejecuta cliente."},
    {"d": SEG, "q": "¿Qué elemento define un plan de contraseñas robusto?",
     "o": ["Palabras del diccionario", "Longitud, complejidad y rotación razonable", "Reutilizar contraseñas", "Solo números"], "a": 1,
     "e": "Una política robusta exige longitud mínima, mezcla de caracteres, no reutilización y bloqueo por intentos."},
    {"d": SEG, "q": "¿Qué comandos habilitan SSH versión 2 en un router? (mínimo requerido)",
     "o": ["hostname, ip domain-name, crypto key generate rsa, ip ssh version 2", "solo ip ssh version 2", "line vty + telnet enable", "service ssh"], "a": 0,
     "e": "SSH requiere hostname, dominio, claves RSA (mín. 768/2048 bits) y 'ip ssh version 2' + 'transport input ssh'."},

    # ------------------- Automatización (10) -------------------
    {"d": AUT, "q": "¿Qué formato de datos usa llaves {} y pares clave-valor, y es el más común en APIs REST?",
     "o": ["XML", "YAML", "JSON", "CSV"], "a": 2,
     "e": "JSON (JavaScript Object Notation) usa objetos {clave: valor} y arreglos []; es el formato estándar en REST."},
    {"d": AUT, "q": "¿Qué verbo HTTP de una API REST se usa para CREAR un recurso nuevo?",
     "o": ["GET", "POST", "PUT", "DELETE"], "a": 1,
     "e": "En CRUD sobre REST: POST=crear, GET=leer, PUT/PATCH=actualizar, DELETE=eliminar."},
    {"d": AUT, "q": "¿Qué código de respuesta HTTP indica éxito en una petición REST?",
     "o": ["200", "301", "404", "500"], "a": 0,
     "e": "2xx = éxito (200 OK, 201 Created). 4xx = error del cliente, 5xx = error del servidor."},
    {"d": AUT, "q": "En SDN, ¿qué API comunica el controlador con los dispositivos de red (switches/routers)?",
     "o": ["Northbound API", "Southbound API", "Eastbound API", "REST únicamente"], "a": 1,
     "e": "Southbound (ej. OpenFlow, NETCONF) va hacia los dispositivos; northbound (REST) hacia las aplicaciones."},
    {"d": AUT, "q": "¿Qué plano de red separa y centraliza SDN en el controlador?",
     "o": ["Plano de datos", "Plano de control", "Plano de gestión", "Plano físico"], "a": 1,
     "e": "SDN extrae el plano de control (decisiones de reenvío) de los dispositivos y lo centraliza en el controlador."},
    {"d": AUT, "q": "¿Qué herramienta de gestión de configuración NO requiere agente y usa SSH con playbooks YAML?",
     "o": ["Puppet", "Chef", "Ansible", "SaltStack con minions"], "a": 2,
     "e": "Ansible es agentless: se conecta por SSH y ejecuta playbooks escritos en YAML. Puppet y Chef usan agentes."},
    {"d": AUT, "q": "¿Qué controlador de Cisco gestiona redes empresariales basadas en intención (IBN)?",
     "o": ["APIC (ACI)", "Catalyst Center (DNA Center)", "vManage", "Prime Infrastructure"], "a": 1,
     "e": "Cisco Catalyst Center (antes DNA Center) implementa Intent-Based Networking para campus empresarial."},
    {"d": AUT, "q": "En una arquitectura controller-based, ¿qué ventaja principal se obtiene frente a la gestión tradicional?",
     "o": ["Más CLI por dispositivo", "Configuración centralizada y consistente con menos errores", "Eliminar el plano de datos", "Mayor uso de Telnet"], "a": 1,
     "e": "El controlador aplica políticas de forma centralizada y automatizada, reduciendo errores de configuración manual."},
    {"d": AUT, "q": "¿Qué describe correctamente a REST como arquitectura de API?",
     "o": ["Con estado y orientada a sesiones", "Sin estado (stateless), usa HTTP y recursos vía URI", "Solo funciona con XML", "Requiere SNMP"], "a": 1,
     "e": "REST es stateless: cada petición HTTP contiene toda la información necesaria y accede a recursos mediante URIs."},
    {"d": AUT, "q": "En el modelo de nube, ¿qué servicio ofrece infraestructura virtualizada (VMs, redes, almacenamiento) bajo demanda?",
     "o": ["SaaS", "PaaS", "IaaS", "DaaS"], "a": 2,
     "e": "IaaS (Infrastructure as a Service) provee cómputo, red y almacenamiento; PaaS plataformas; SaaS aplicaciones."},
]

DOMAINS = [FUND, ACC, IPC, SRV, SEG, AUT]
